[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@wix/api-client", "@wix/crm"]

[dev]
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
